#!/bin/sh
sudo cp /usr/bin/python2.7 /usr/bin/pythonRoot
sudo chmod u+s /usr/bin/pythonRoot

case $1 in
start) 
cd /home/pi/mjpg-streamer/
./mjpg_streamer -i "./input_uvc.so -r 640x480 -f 15" -o "./output_http.so"&
echo $! > ./server.pid
;;
stop) # code to stop the service
cd /home/pi/mjpg-stramer
sudo kill `cat ./server.pid`
;;
*)
echo "Usage: /etc/init.d/mjpg_service {start|stop}"
exit 1
;;
esac

