#!/bin/sh
sudo cp /usr/bin/python2.7 /usr/bin/pythonRoot
sudo chmod u+s /usr/bin/pythonRoot

case $1 in
start) 
cd /home/pi/Shapextractor
sudo python -m CGIHTTPServer 7000 &
echo $! > ./server.pid
;;
stop) # code to stop the service
cd /home/pi/Shapextractor
sudo kill `cat ./server.pid`
;;
*)
echo "Usage: /etc/init.d/Shape_service {start|stop}"
exit 1
;;
esac

